logo: "/assets/images/Abiva Logo 2.png"
masthead_title: "Abiva Publishing House Inc."
title: "'Insert product name' by Abiva Publishing House Inc."
email: 
description: >-
  This is a test site for the DesignExer given by APH.
baseurl: ""
url: ""
twitter_username: John Smitht
github_username:  John Smithg

remote_theme: "mmistakes/minimal-mistakes@4.26.2" 
plugins:
  - jekyll-include-cache
