source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
# gem "wdm", "~> 0.1.0" if Gem.win_platform?

group :jekyll_plugins do
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "tzinfo-data", "1.2025.1"
  gem "jekyll-algolia", "1.7.1"
  gem "webrick", "1.9.1"
  gem "algolia_html_extractor", "2.6.4"
  gem "algoliasearch", "1.27.5"
  gem "filesize", "0.2.0"
  gem "json", "2.10.2"
  gem "progressbar", "1.13.0"
  gem "verbal_expressions", "0.1.5"
  gem "dnsruby", "1.72.4"
  gem "csv", "3.3.2"
  gem "i18n", "1.14.7"
  gem "commonmarker", "0.23.11"
  gem "rubyzip", "2.4.1"
  gem "rexml", "3.4.1"
  gem "concurrent-ruby", "1.3.5"
  gem "faraday", "2.12.2"
  gem "activesupport", "8.0.2"
  gem "httpclient", "2.9.0"
  gem "logger", "1.6.6"
  gem "execjs", "2.10.0"
  gem "faraday-net_http", "3.4.0"
  gem "benchmark", "0.4.0"
  gem "bigdecimal", "3.1.9"
  gem "connection_pool", "2.5.0"
  gem "minitest", "5.25.4"
  gem "securerandom", "0.4.1"
  gem "uri", "1.0.3"
  gem "mutex_m", "0.3.0"
  gem "net-http", "0.6.0"
  
end